#!/bin/bash
#===============================================================================
# aws-r53 : AWS Route53 manage script
# Date    :  2018/04/15 Start
# Copyright: Original code by Yusuke Komori.
#                  Copyright (c) 2018-2019. Yusuke Komori, All rights reserved.
#===============================================================================

SCRIPT_BASE=`echo $(cd $(dirname $0); pwd)`
SCRIPT_NAME=`basename $0`

AWS_OPT="--output json route53"
R53="aws $AWS_OPT"
RC_FILE0="/etc/aws-r53rc"
RC_FILE="${HOME}/.aws-r53rc"

R53_ENV=()

#-------------------------------------------------------------------------------
#- common functions ------------------------------------------------------------

__setupcolor() { #{{{
  local C
  local COLOR=(BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE GRAY)
  local STYLE=(OFF BOLD REV UL)

  # Escape sequence
  ESC="\e["
  ESCEND=m

  # define empty valiable
  for C in ${STYLE[@]}; do
    eval "C_${C}="
  done
  for C in ${COLOR[@]}; do
    eval "C_${C}="
    eval "C_B_${C}="
  done

  tty -s || return
  C_OFF=`tput sgr0`   # Reset attribute
  C_BOLD=`tput bold`
  C_REV=`tput rev`    # Reverse mode
  C_UL=`tput smul`    # Underline mode

  # Background
  C_B_BLACK=`tput setab 0`
  C_B_RED=`tput setab 1`
  C_B_GREEN=`tput setab 2`
  C_B_YELLOW=`tput setab 3`
  C_B_BLUE=`tput setab 4`
  C_B_MAGENTA=`tput setab 5`
  C_B_CYAN=`tput setab 6`
  C_B_WHITE=`tput setab 7`
  C_B_GRAY=`tput setab 102`

  # Foreground
  C_BLACK=`tput setaf 0`
  C_RED=`tput setaf 1`
  C_GREEN=`tput setaf 2`
  C_YELLOW=`tput setaf 3`
  C_BLUE=`tput setaf 4`
  C_MAGENTA=`tput setaf 5`
  C_CYAN=`tput setaf 6`
  C_WHITE="${C_BOLD}`tput setaf 7`"
  C_GRAY=`tput setaf 102`

  RES_COL=60
  MOVE_TO_COL="echo -en \\033[${RES_COL}G"
}
#}}}

__syslog() { #{{{
  [[ -n "${DRY_RUN}" ]] && return 
  [ ! "$SCRIPT_NAME" ] && local SCRIPT_NAME=`basename $0`
  if [ "$LOG_TAG" ]; then
    local TAG="${LOG_TAG}/${SCRIPT_NAME}"
  else
    local TAG="${SCRIPT_NAME}"
  fi

  local FACILITY=user
  [[ "$LOG_FACILITY" ]] && FACILITY=$LOG_FACILITY

  local LOG_LEVEL=info
  [[ "$2" ]] && LOG_LEVEL="$2"

  if [[ "$1" ]]; then
    logger -t "$TAG" -p "${FACILITY}.${LOG_LEVEL}" "$1"
  else
    local OLDIFS="$IFS"
    IFS=
    while read LOG_LINE; do
      logger -t "$TAG" -p "${FACILITY}.${LOG_LEVEL}" "$LOG_LINE"
    done
    IFS="$OLDIFS"
  fi
}
#}}}

__show_ok() { #{{{
  [ "${SILENT_MODE}" ] && return
  [[ "$1" && "$1" -gt 0 ]] && echo -en "\\033[${1}G"
  echo -en "[ ${C_GREEN}OK${C_OFF}"
  [ "$2" ] && echo " ]$2" || echo " ]"
}
#}}}

__show_info() { #{{{
  [[ -n "${SILENT_MODE}" ]] && return
  [[ "$1" == "-n" ]] && echo -en "${C_CYAN}${2}${C_OFF}" || echo -e "${C_CYAN}${1}${C_OFF}"
}
#}}}

__show_error() { #{{{
  local MSG="$1"
  if [[ -z "$MSG" ]]; then
    MSG=`sed -re '/^[ \t]*$/d' | tr -d "\n"`
  fi
  tty -s || __syslog "[ERROR] $MSG" 'error'
  echo -e "[${C_RED}ERROR${C_OFF}] $MSG"
}
#}}}

__error_end() { #{{{
  __show_error "$1"; exit 1
}
#}}}


#-------------------------------------------------------------------------------
#- functions -------------------------------------------------------------------

# usage
#{{{
_usage() {
  [[ -n "$1" ]] && __show_error "$1"
  ( ! tty -s || [[ -n "$1" ]] ) && __syslog "ERROR: $1" 'err'
  cat <<- EOM
	${C_WHITE}Usege:${C_OFF}
	  $SCRIPT_NAME (get|update|auto-update|show-ip) [-p PROFILE] [-z ZONE_ID] [-n NAME] [-t TYPE] [-l TTL] [-v VALUE] [-wVDh]
	    get:         Get DNS record (type and name should be specified)
	    update:      Update DNS A record
	    auto-update: Update DNS A record using IP_SUPPLIER_SCRIPT
	    show-ip:     Show IP address using IP_SUPPLIER_SCRIPT
	          -p : aws-cli's profile name (Option)
	          -z : Route53's Hosted zone ID
	          -n : DNS record name (ex: example.com)
	          -t : DNS record type (ex: A, CNAME, TXT, ...)
	          -v : DNS record value
	          -l : TTL to set (default is 300)
	          -V : Verbode mode
	          -D : dry-run
	          -w : Wait for UPSERT change info to be INSYNC
	          -h : display usage
	
	${C_WHITE}Configuration file:${C_OFF}
	  You can configure some options in '~/.aws-r53rc' or '${RC_FILE0}'. Here is example configuration.
	
	      AWS_PATH=<PATH_TO_AWS_CLI> (option)
	      AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
	      AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	      ZONE_ID=XXXXXXXXXXXXXXXXXXXX
	      PROFILE=aws-r53
	      IP_SUPPLIER_SCRIPT=\"/usr/local/bin/xxxx\"
	
	  If both files are specified, ~/.aws-r53rc will take precedence.
	
	${C_WHITE}Logging:${C_OFF}
	  ${SCRIPT_NAME} outputs log message to syslog with logging tag "${SCRIPT_NAME}".
	  You can check logs with following command.
	
	    sudo grep " ${SCRIPT_NAME}: " /var/log/messages
	
	${C_WHITE}Example:${C_OFF}
	  * Get all record set of specified hosted zone id.
	      $SCRIPT_NAME get -z ZONE_ID -V
	
	  * Get Sepcified DNS record.
	      $SCRIPT_NAME get -z ZONE_ID -t A -n example.com
	
	  * Update DNS A record and wait for synchronization.
	      $SCRIPT_NAME update -z ZONE_ID -t A -n example.com -v IP_ADDRESS -w
	
	  * Auto-Update DNS A record.
	      (IP address is auto-accuired using IP_SUPPLIER_SCRIPT specified in aws-r53rc)
	      $SCRIPT_NAME auto-update -z ZONE_ID -t A -n example.com -w
	EOM
  exit 1
}
#}}}

_get_value() {
#{{{
  __syslog "[get] ZoneID:$ZONE_ID"
  T_RESULT=`mktemp -p /dev/shm`
  T_ERROR=`mktemp -p /dev/shm`
  $R53 list-resource-record-sets --hosted-zone-id="$ZONE_ID" > $T_RESULT 2> $T_ERROR
  if [[ $? -eq 0 ]]; then
    if [[ ! "$VERBOSE" ]]; then
      [[ "$TYPE" ]] || __error_end "Type should be specified." 
      [[ "$NAME" ]] || __error_end "Name should be specified." 
      cat $T_RESULT | jq -r ".ResourceRecordSets[] | if .Type == \"$TYPE\" and .Name == \"$NAME.\" then . else empty end | .ResourceRecords[].Value"
    else
      cat $T_RESULT | jq .
    fi
  else
    cat $T_ERROR | __error_end
  fi
}
#}}}

_update() {
#{{{
  local DOMAIN=$1
  local TYPE=$2
  local VALUE=$3
  local TTL=$4
  local CHANGE_INFO_ID

  [[ ! "$DOMAIN" ]] && _usage "Domain is not specified."
  [[ ! "$TYPE" ]] && _usage "Type is not specified."
  [[ ! "$VALUE" ]] && _usage "Value is not specified."
  [[ ! "$TTL" ]] && TTL=300

  T_BATCH=`mktemp -p /dev/shm`
  T_RESULT=`mktemp -p /dev/shm`
  T_ERROR=`mktemp -p /dev/shm`
  _create_json "$DOMAIN" "$TYPE" "$VALUE" "$TTL" >> $T_BATCH

  (echo -n "[update] ZoneID:$ZONE_ID "; cat $T_BATCH | jq -Mc .) | __syslog
  if [[ ! "$DRY_RUN" ]]; then
    $R53 change-resource-record-sets --hosted-zone-id="$ZONE_ID" --change-batch file://$T_BATCH > $T_RESULT 2> $T_ERROR
    if [[ $? -eq 0 ]]; then
      CHANGE_INFO_ID=`cat $T_RESULT | jq -Mrc '.ChangeInfo.Id'`
      __syslog "[update] request succeeded. ChangeInfoID:$CHANGE_INFO_ID"
      if [[ "$WAIT" ]]; then
        _wait_for $CHANGE_INFO_ID
      else
        echo $CHANGE_INFO_ID
      fi
    else
      cat $T_ERROR | __error_end
    fi
  else
    # dry-run
    echo "$R53 change-resource-record-sets --hosted-zone-id=\"$ZONE_ID\" --change-batch file://$T_BATCH"
    echo -n "change-batch: "
    cat $T_BATCH
  fi
}
#}}}

_auto_update() { #{{{
  local DOMAIN=$1
  local TYPE=$2
  local TTL=$3

  local IP=`_show_ip SILENT`
  [[ ! "$IP" ]] && IP='(empty result)'
  _validate_ip "$IP" || __error_end "Invalid address. : $IP"

  _update "$DOMAIN" "$TYPE" "$IP" "$TTL"
}
#}}}

_wait_for() {
#{{{
  local ID=$1
  echo -ne "${C_CYAN}Waiting for ${ID}${C_OFF} "

  T_RESULT=`mktemp -p /dev/shm`
  while :; do
    sleep 10
    __syslog "[update] Waiting for $CHANGE_INFO_ID"
    $R53 get-change --id "$ID" > $T_RESULT
    if [[ $? -eq 0 ]]; then
      local STATUS=`cat $T_RESULT | jq -r '.ChangeInfo.Status'`
      if [[ $STATUS == 'INSYNC' ]]; then
        __syslog "[update] $CHANGE_INFO_ID INSYNC"
        echo -e " [ ${C_GREEN}OK${C_OFF} ]"
        break
      fi
      echo -n '.'
    else
      __syslog "[update] Waiting for $CHANGE_INFO_ID failed."
      echo -e " [ ${C_RED}FAILED${C_OFF} ]"
      exit
    fi
  done
}
#}}}

_script_end() {
#{{{
  [[ -f "$T_BATCH" ]] && rm "$T_BATCH"
  [[ -f "$T_RESULT" ]] && rm "$T_RESULT"
  [[ -f "$T_ERROR" ]] && rm "$T_ERROR"
}
trap '_script_end' EXIT
#}}}

_create_json() {
#{{{
  local NAME=$1
  local TYPE=$2
  local VALUE=$3
  VALUE=`sed -re 's|"|\\\\"|g' <<<"$VALUE"`
  local TTL=$4
  cat <<EOJ
{
  "Comment" : "",
  "Changes" : [
    {
      "Action" : "UPSERT",
      "ResourceRecordSet" : {
        "Name" : "$NAME",
        "Type" : "$TYPE",
        "TTL" : $TTL,
        "ResourceRecords" : [
          {
            "Value": "$VALUE"
          }
        ]
      }
    }
  ]
}
EOJ
}
#}}}

_show_ip() {
#{{{
  local SILENT="$1"
  if [[ ! "${IP_SUPPLIER_SCRIPT}" ]]; then
    __error_end "IP_SUPPLIER_SCRIPT is not specified."
  fi
  local SCRIPT=(${IP_SUPPLIER_SCRIPT})
  if [[ ! -x "${SCRIPT[0]}" ]]; then
    __error_end "${SCRIPT[0]} is not executable."
  fi
  local DELAY=(5 10 20 35 60 120 120)
  local CNT=0

  while [[ $CNT -lt ${#DELAY[@]} ]]; do
    # execute it
    local IP=`${SCRIPT[@]}`

    # validate it
    if _validate_ip "$IP"; then
      echo "${IP}"
      return
    else
      # retry after sleep
      __syslog "Invalid IP address, retry after ${DELAY[$CNT]}sec... : $IP"
      sleep ${DELAY[$CNT]}
      CNT=$(($CNT + 1))
    fi
  done

  if [[ ! "$SILENT" ]]; then
    __error_end "Couldn't get IP address. (Executed: ${IP_SUPPLIER_SCRIPT} Result:$IP)"
  fi
}
#}}}

_validate_ip() { #{{{
  local IP="$1"
  [[ -z "$IP" || "$IP" = "0.0.0.0" || `wc -l <<<"$IP"` -gt 1 ]] && return 1
  local REGEX='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
  [[ -n `sed -nre "/${REGEX}/p" <<<"$IP"` ]] && return 0 || return 1
}
#}}}

#-------------------------------------------------------------------------------
#- Main process ----------------------------------------------------------------
#-------------------------------------------------------------------------------
tty -s && __setupcolor

#- Check dependencies ----------------------------------------------------------
#{{{
which aws > /dev/null 2>&1 || __error_end "aws-cli is not installed."
which jq > /dev/null 2>&1 || __error_end "jq is not installed."
#}}}

#- Get subcommand --------------------------------------------------------------
#{{{
CMD="$1"
case "$CMD" in
  get) ;;
  update) ;;
  auto-update) ;;
  update-acme-challenge) ;;
  show-ip) ;;
  -h) _usage ;;
  *) _usage "Unknown sub command" ;;
esac
shift 1
#}}}

#- Get options -----------------------------------------------------------------
#{{{
while getopts p:z:n:t:l:v:wDVh OPT; do
  case "$OPT" in
    p) PROFILE=$OPTARG
      ;;
    z) ZONE_ID=$OPTARG
      ;;
    n) NAME=$OPTARG
      ;;
    t) TYPE=$OPTARG
      ;;
    l) TTL=$OPTARG
      ;;
    v) VALUE=$OPTARG
      ;;
    w) WAIT=yes
      ;;
    V) VERBOSE=yes
      ;;
    D) DRY_RUN=yes
      ;;
    h|\?) _usage
      ;;
  esac
done
shift `expr $OPTIND - 1`
#}}}

#- Check options ---------------------------------------------------------------
#{{{
if [[ -f "$RC_FILE0" ]]; then
  source $RC_FILE0
  __syslog "$RC_FILE0 loaded."
fi
if [[ -f "$RC_FILE" ]]; then
  source $RC_FILE
  __syslog "$RC_FILE loaded."
fi

# aws path is specified
if [[ "$AWS_PATH" ]]; then
  [[ -x "$AWS_PATH" ]] || __error_end "$AWS_PATH is not found."
  __syslog "AWS_PATH : $AWS_PATH"
  R53="${AWS_PATH} ${AWS_OPT}"
fi

[[ ! "$ZONE_ID" ]] && _usage "Hosted zone id is not specified."
if [[ "$AWS_ACCESS_KEY_ID" ]]; then
  __syslog "AWS_ACCESS_KEY_ID is specified."
  R53_ENV+=("AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID")
fi
if [[ "$AWS_SECRET_ACCESS_KEY" ]]; then
  __syslog "AWS_SECRET_ACCESS_KEY is specified."
  R53_ENV+=("AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY")
fi
if [[ "$PROFILE" ]]; then
  __syslog "AWS-CLI Profile:$PROFILE"
  R53="$R53 --profile $PROFILE"
fi
if [[ ! -z "$R53_ENV" ]]; then
  R53="env ${R53_ENV[@]} $R53"
fi
#}}}

#- Main process ----------------------------------------------------------------
[[ $VERBOSE ]] && echo "Hosted zone id: $ZONE_ID"

case $CMD in
  get)
    _get_value
    ;;
  update)
    _update "$NAME" "$TYPE" "$VALUE" "$TTL"
    ;;
  auto-update)
    _auto_update "$NAME" "$TYPE" "$TTL"
    ;;
  update-acme-challenge)
    _update "_acme-challenge.${NAME}" TXT "\"${VALUE}\"" "$TTL"
    ;;
  show-ip)
    _show_ip
    ;;
esac

# vim: ts=2 sw=2 sts=2 et nu foldmethod=marker
